# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: hexo-theme-wang
subtitle: 'ä¸€ä¸ªç®€çº¦ä½†ä¸ç®€å•çš„hexoä¸»é¢˜'
description: 'æ­£åœ¨ç¼–å†™ä½¿ç”¨æ–‡æ¡£'
keywords: hexo,theme,blog,web,wang,xingwangzhe
author: xingwangzhe
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://hexo-theme-wang.needhelp.icu
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true


date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 12
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: wang

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
# deploy:
#   type: git
#  # repo: 
#   repo: 
#   branch: master


feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 500
  hub:
  content:
  content_limit: 300
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

hexo_tips:
  warning:
    icon: 'âš '
    style:
      border: '#ffb100'
      light:
        background: '#fff8e6'
      dark:
        background: '#3d371f'
  danger:
    icon: 'â›”'
    style:
      border: '#ff4545'
      light:
        background: '#ffeded'
      dark:
        background: '#3d2222'
  tip:
    icon: 'ğŸ’¡'
    style:
      border: '#409eff'
      light:
        background: '#e6f4ff'
      dark:
        background: '#1f2f3d'
  mention:
    icon: 'ğŸ’¬'
    style:
      border: '#b45fff'
      light:
        background: '#f3e6ff'
      dark:
        background: '#2f1f3d'
  recommend:
    icon: 'ğŸ‘'
    style:
      border: '#67c23a'
      light:
        background: '#e6ffe6'
      dark:
        background: '#1f3d1f'
  note:
    icon: 'ğŸ“'
    style:
      border: '#9e9e9e'
      light:
        background: '#f5f5f5'
      dark:
        background: '#363636'
  info:
    icon: 'â„¹ï¸'
    style:
      border: '#03a9f4'
      light:
        background: '#e3f2fd'
      dark:
        background: '#1f313d'
  success:
    icon: 'âœ…'
    style:
      border: '#4caf50'
      light:
        background: '#e8f5e9'
      dark:
        background: '#1f3d24'
  error:
    icon: 'âŒ'
    style:
      border: '#f44336'
      light:
        background: '#ffebee'
      dark:
        background: '#3d1f22'
  bug:
    icon: 'ğŸ›'
    style:
      border: '#e91e63'
      light:
        background: '#fce4ec'
      dark:
        background: '#3d1f2a'
  todo:
    icon: 'ğŸ“‹'
    style:
      border: '#9c27b0'
      light:
        background: '#f3e5f5'
      dark:
        background: '#2f1f3d'
  example:
    icon: 'ğŸ”'
    style:
      border: '#ff9800'
      light:
        background: '#fff3e0'
      dark:
        background: '#3d311f'
  quote:
    icon: 'ğŸ’­'
    style:
      border: '#607d8b'
      light:
        background: '#eceff1'
      dark:
        background: '#1f292d'
  link:
    icon: 'ğŸ”—'
    style:
      border: '#3f51b5'
      light:
        background: '#e8eaf6'
      dark:
        background: '#1f2137'
  code:
    icon: 'ğŸ’»'
    style:
      border: '#616161'
      light:
        background: '#fafafa'
      dark:
        background: '#363636'
  update:
    icon: 'ğŸ”„'
    style:
      border: '#009688'
      light:
        background: '#e0f2f1'
      dark:
        background: '#1f3734'
  star:
    icon: 'â­'
    style:
      border: '#ffd700'
      light:
        background: '#fffde7'
      dark:
        background: '#3d3a1f'
  time:
    icon: 'âŒ›'
    style:
      border: '#795548'
      light:
        background: '#efebe9'
      dark:
        background: '#332824'
  question:
    icon: 'â“'
    style:
      border: '#ff5722'
      light:
        background: '#fbe9e7'
      dark:
        background: '#3d261f'
  ai:
    icon: 'ğŸ¤–'
    style:
      border: '#00bcd4'
      light:
        background: '#e0f7fa'
      dark:
        background: '#1f353d'
hexo_graph:
  theme: "dark" # light/darkï¼Œé»˜è®¤æ˜¯ light
  #echarts_js: "/vendor/js/echarts.min.js" # å¯è‡ªå®šä¹‰åœ°å€ï¼Œä¸å¡«å†™é»˜è®¤ä¸ºjsdçš„cdn


hexo_pro:
  username: admin
  password: 123
  avatar:
  secret: xxx

sitemap:
  path:
    - sitemap.xml
  rel: true
  tags: true
  categories: true


# markdown æ¸²æŸ“å¼•æ“é…ç½®
# é»˜è®¤æ˜¯hexo-renderer-marked
# å½“å‰ä¸ºhexo-renderer-markdown-it
markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: false
    langPrefix: 'language-'
    breaks: true
    linkify: true
    typographer: true
    quotes: 'â€œâ€â€˜â€™'
  enable_rules:
  disable_rules:
  plugins:
  - name: '@renbaoshuo/markdown-it-katex'
    options:
      skipDelimitersCheck: true
  anchors:
    level: 1 # ä»ä¸€çº§æ ‡é¢˜å¼€å§‹æ¸²æŸ“ï¼Œå¦åˆ™æ— æ³•æ­£ç¡®ç”¨ç›®å½•é“¾æ¥
    collisionSuffix: ''
    permalink: false
    permalinkClass: 'header-anchor'
    permalinkSide: 'left'
    permalinkSymbol: 'Â¶'
    case: 0
    separator: '-'
  images:
    lazyload: false
    prepend_root: false
    post_asset: false
  inline: false  # https://markdown-it.github.io/markdown-it/#MarkdownIt.renderInline
